services:
  backend:
    type: web
    name: todo-list-backend
    env: docker
    docker:
      dockerfilePath: ./backend/Dockerfile  # Correct path to backend Dockerfile
    healthCheckPath: /get_tasks.php
    autoDeploy: true

  frontend:
    type: web
    name: todo-list-frontend
    env: docker
    docker:
      dockerfilePath: ./frontend/Dockerfile  # Correct path to frontend Dockerfile
    healthCheckPath: /
    autoDeploy: true
